export default Images = {
  settings: require('../assets/settings.png'),
  background: require('../assets/background.png'),
  Logo: require('../assets/Logo1.png'),
  Rectangle: require('../assets/Rectangle.png'),
  user: require('../assets/user.png'),
  Google: require('../assets/Google.png'),
  Facebook: require('../assets/Facebook.png'),
  profileAlarm: require('../assets/profileAlarm.png'),
  profileInsert: require('../assets/profileInsert.png'),
  profileMusic: require('../assets/profileMusic.png'),
  profilePlaylist: require('../assets/profilePlaylist.png'),
  profilePlaylist2: require('../assets/profilePlaylist2.png'),
  profileRecord: require('../assets/profileRecord.png'),
  profileStar: require('../assets/profileStar.png'),
  SongTemplate: require('../assets/SongTemplate.png'),
  locked: require('../assets/locked.png'),
};
